keys:
  - &lunch age1s2wrj0e8c2p09rxlkrlghdmed473zl46zp0j64mzlgp66gj80d2q9pyve3
  - &lunchbox age1qvq5uw669mxfu39nuxfjl7wrkr6zpvyxpezff3k20m4sdzas03wslm8gdn
creation_rules:
  - path_regex: secrets/lunch.yaml$
    key_groups:
      - age:
          - *lunch
  - path_regex: secrets/lunchbox.yaml$
    key_groups:
      - age:
          - *lunchbox
