keys:
  - &lunchbox age1fe2alznmwldqrnlx09n4e7hfc3kflm2h9lmgem54kcadze5kp53qjuyrqy
  - &lunch age1s2wrj0e8c2p09rxlkrlghdmed473zl46zp0j64mzlgp66gj80d2q9pyve3
  - &db age1705unyak8jq28k5ujfau4m8kyusaepyzky6dhwfl29tppaa73d8shx6y7n
creation_rules:
  - path_regex: secrets/bentobox.yaml$
    key_groups:
      - age:
          - *lunchbox
          - *lunch
          - *db

  - pgp: 63115D201A707CDD37CA1CFBF87D2D8C2444FA84
